export const initialData = {
  price: 0,
  discount: 0,
  extra_discount: 0,
  subtotal: 0,
  shipping_fee: 0,
  tax: 0,
  total: 0,
  paid_amount: 0,
  order_status: 2,
  shipping_status: 1,
  payment_status: 1,
  shipping_method: 1,
  payment_method: 3,
  payment_channel: 1,
  weight: 0,
  courier_enable: false,
  courier_store_id: 0,
  delivery_type: 48,
  partial_payment: true,
  products: [
    {
      id: 0,
      attribute_id: 0,
      discount: 0,
      price: 0,
      qty: 1,
      tax: 0,
      total_price: 0,
      weight: 0,
      stock: 0,
      offer: 0,
      rate: 0,
    },
  ],
  order_note: '',
  customer: {
    id: 0,
    country: '',
    name: '',
    email: '',
    msisdn: '',
    type: 'guest',
    address: {
      id: 0,
      address_type: 'Home',
      name: '',
      msisdn: '',
      region_id: 0,
      city_id: 0,
      zone_id: 0,
      area_id: 0,
      street_address: '',
    },
  },
}
