name: Node.js CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm i -f
          npm run build
          # pm2 restart
